<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LiveSPICE.Avalonia</AssemblyName>
    <Product>LiveSPICE.Avalonia</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
    <ProjectReference Include="..\Circuit\Circuit.csproj" />
    <ProjectReference Include="..\ComputerAlgebra\ComputerAlgebra\ComputerAlgebra.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
  </ItemGroup>
</Project>