<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>livespice</AssemblyName>
    <RootNamespace>LiveSPICE.CLI</RootNamespace>
    <Product>LiveSPICE.CLI</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Audio\Audio.csproj" />
    <ProjectReference Include="..\Circuit\Circuit.csproj" />
    <ProjectReference Include="..\ComputerAlgebra\ComputerAlgebra\ComputerAlgebra.csproj" />
    <ProjectReference Include="..\CoreAudio\CoreAudio.csproj" />
    <ProjectReference Include="..\LiveSPICE.PluginCore\LiveSPICE.PluginCore.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>
</Project>
