<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>LiveSPICE.Headless</AssemblyName>
    <Product>LiveSPICE.Headless</Product>
    <Copyright>Copyright © 2026</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Circuit\Circuit.csproj" />
  </ItemGroup>
</Project>